# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SheetEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateTimeField(editable=False, verbose_name='Date Received')),
                ('consignment_id', models.CharField(max_length=20, verbose_name='Consignment ID')),
                ('consignment_no', models.CharField(max_length=20, verbose_name='Consignment No')),
                ('reference', models.CharField(max_length=30, verbose_name='Reference #1')),
                ('return_no', models.CharField(max_length=30, verbose_name='Return No')),
                ('sender', models.CharField(max_length=30, verbose_name='Sender Name')),
                ('consignee', models.CharField(max_length=50, verbose_name='Consignee Name')),
                ('consignee_suburb', models.CharField(max_length=50, verbose_name='Consignee suburb')),
                ('packets', models.IntegerField(verbose_name='Packets')),
                ('kgs_used', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kgs Used')),
                ('rate_per_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rate Per Kg')),
                ('min_charge', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Minimum Charge')),
                ('doc_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Document Fee')),
                ('fuel_surcharge', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fuel Surchare Ex. Vat')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount incl. VAT')),
            ],
        ),
        migrations.CreateModel(
            name='SheetFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_file', models.FileField(upload_to='sheet_uploads/', verbose_name='Spreadsheet File')),
                ('sheet_hash', models.TextField(editable=False, max_length=256, unique=True)),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Date Uploaded')),
                ('sheet_date', models.DateField(editable=False, null=True, verbose_name='Date Of Sheet')),
            ],
        ),
    ]
