# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SheetFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_file', models.FileField(upload_to='sheet_uploads/', verbose_name='Spreadsheet File')),
                ('sheet_hash', models.TextField(editable=False, max_length='256', unique=True)),
                ('created', models.DateTimeField(editable=False, verbose_name='Date Uploaded')),
                ('sheet_date', models.DateField(editable=False, null=True, verbose_name='Date Of Sheet')),
            ],
        ),
    ]
