# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0002_auto_20160815_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workbookfile',
            old_name='path',
            new_name='file',
        ),
    ]
