# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-12 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0002_auto_20160811_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_invoiced', models.DateTimeField(editable=False, verbose_name='Date Invoiced')),
                ('consolidation_no', models.CharField(max_length=20, verbose_name='Consolidation No')),
                ('trip_no', models.IntegerField(verbose_name='Trip no')),
                ('from_hub_code', models.IntegerField(verbose_name='From Hub Code')),
                ('from_hub_name', models.CharField(max_length=30, verbose_name='From Hub Name')),
                ('from_postal_code', models.IntegerField(verbose_name='From Postal Code')),
                ('from_area_class', models.CharField(max_length=3, verbose_name='From Area Class')),
                ('sender', models.CharField(max_length=30, verbose_name='Sender Name')),
                ('to_hub_code', models.IntegerField(verbose_name='To Hub Code')),
                ('to_hub_name', models.CharField(max_length=30, verbose_name='To Hub Name')),
                ('to_postal_code', models.IntegerField(verbose_name='To Postal Code')),
                ('to_area_class', models.CharField(max_length=3, verbose_name='To Area Class')),
                ('consignee', models.CharField(max_length=50, verbose_name='Consignee Name')),
                ('consignee_town', models.CharField(max_length=50, verbose_name='Consignee Town')),
                ('invoice_type', models.CharField(max_length=10, verbose_name='Invoice Type')),
                ('measurement_unit', models.CharField(max_length=20, verbose_name='Unit Of Measurement')),
                ('actual_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Actual Weight')),
                ('volume_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Volume Weight')),
                ('cons_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cons Weight')),
                ('over_3k_check', models.BooleanField(verbose_name='Over 3000 check')),
                ('insurance_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Insurance Value')),
                ('rate_charge_add_on', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rate Charge Add On')),
                ('sanral_hrp_charge', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sanral HRP Charge')),
                ('outlying_surcharge', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Outlying Surcharge')),
                ('saturday_surcharge', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saturday Surcharge')),
                ('pub_hol_surcharge', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Public Holiday Surcharge')),
                ('bdd_surcharge', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='BDD Surcharge')),
                ('aaa_surcharge', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='AAA Surcharge')),
                ('sales_percentage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Percentage of Sales')),
                ('dawn_delivery_charge', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Dawn Delivery Charge')),
                ('fridgeline_charge', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fridgeline Charge')),
                ('high_risk_charge', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='High Risk Charge')),
                ('collection_charge', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Collection Charge')),
                ('insurance_by_charge', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Insurance By Percentage Charge')),
                ('midnight_surcharge', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Midnight Surcharge')),
                ('sanral_charges', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sanral Charges')),
                ('sanral_zone', models.CharField(max_length=3, verbose_name='Sanral Zone')),
                ('waybill_insurance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Insurance per Waybill')),
                ('sunday_charge', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sunday Charge')),
                ('home_delivery', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Home Delivery')),
                ('re_delivery', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Re-Delivery')),
                ('online_delivery', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Online Delivery')),
                ('tech_doc_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Technology Doc Fee')),
                ('pda', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PDA')),
                ('mpod', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='MPOD')),
                ('fuel_surcharge_percentage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fuel Surcharge Percentage')),
                ('amount_excl_vat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Excl. VAT')),
                ('VAT', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='VAT')),
            ],
        ),
    ]
