# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-12 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0003_sheetentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetfile',
            name='sheet_hash',
            field=models.TextField(editable=False, max_length=256, unique=True),
        ),
    ]
