# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0003_auto_20160815_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbookentry',
            name='service_level',
            field=models.IntegerField(default=406, verbose_name='Service Level'),
            preserve_default=False,
        ),
    ]
