# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0004_workbookentry_service_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workbookentry',
            name='sender',
            field=models.CharField(max_length=255, verbose_name='Sender Name'),
        ),
    ]
