# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0005_auto_20160815_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workbookentry',
            name='reference',
            field=models.CharField(max_length=255, verbose_name='Reference #1'),
        ),
    ]
