# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-26 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0008_auto_20160826_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workbookentry',
            name='return_no',
            field=models.CharField(max_length=50, verbose_name='Return No'),
        ),
    ]
