# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-30 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0010_auto_20160826_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbookfile',
            name='name',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
    ]
