from django.db import models

class SheetFile(models.Model):

    sheet_file = models.FileField('Spreadsheet File', upload_to='sheet_uploads/')
    sheet_hash = models.TextField(unique=True, max_length=256, editable=False)
    created = models.DateTimeField('Date Uploaded', editable=False, auto_now=True)
    sheet_date = models.DateField('Date Of Sheet', editable=False, null=True)


class SheetEntry(models.Model):

    date_invoiced = models.DateTimeField('Date Invoiced', editable=False)
    consolidation_no = models.CharField('Consolidation No', max_length=20)
    trip_no = models.IntegerField('Trip no')
    from_hub_code = models.IntegerField('From Hub Code')
    from_hub_name = models.CharField('From Hub Name', max_length=30)
    from_postal_code = models.IntegerField('From Postal Code')
    from_area_class = models.CharField('From Area Class', max_length=3)
    sender = models.CharField('Sender Name', max_length=30)
    to_hub_code = models.IntegerField('To Hub Code')
    to_hub_name = models.CharField('To Hub Name', max_length=30)
    to_postal_code = models.IntegerField('To Postal Code')
    to_area_class = models.CharField('To Area Class', max_length=3)
    consignee = models.CharField('Consignee Name', max_length=50)
    consignee_town = models.CharField('Consignee Town', max_length=50)
    invoice_type = models.CharField('Invoice Type', max_length=10)
    measurement_unit = models.CharField('Unit Of Measurement', max_length=20)
    actual_weight = models.DecimalField('Actual Weight', max_digits=10, decimal_places=2)
    volume_weight = models.DecimalField('Volume Weight', max_digits=10, decimal_places=2)
    cons_weight = models.DecimalField('Cons Weight', max_digits=10, decimal_places=2)
    over_3k_check = models.BooleanField('Over 3000 check')
    insurance_value = models.DecimalField('Insurance Value', max_digits=10, decimal_places=2)
    rate_charge_add_on = models.DecimalField('Rate Charge Add On', max_digits=10, decimal_places=2)
    sanral_hrp_charge = models.DecimalField('Sanral HRP Charge', max_digits=10, decimal_places=2)
    outlying_surcharge = models.DecimalField('Outlying Surcharge', max_digits=10, decimal_places=2)
    saturday_surcharge = models.DecimalField('Saturday Surcharge', max_digits=10, decimal_places=2)
    pub_hol_surcharge = models.DecimalField('Public Holiday Surcharge', max_digits=10, decimal_places=2)
    bdd_surcharge = models.DecimalField('BDD Surcharge', max_digits=10, decimal_places=2)
    aaa_surcharge = models.DecimalField('AAA Surcharge', max_digits=10, decimal_places=2)
    sales_percentage = models.DecimalField('Percentage of Sales', max_digits=10, decimal_places=2)
    dawn_delivery_charge = models.DecimalField('Dawn Delivery Charge', max_digits=10, decimal_places=2)
    fridgeline_charge = models.DecimalField('Fridgeline Charge', max_digits=10, decimal_places=2)
    high_risk_charge = models.DecimalField('High Risk Charge', max_digits=10, decimal_places=2)
    collection_charge = models.DecimalField('Collection Charge', max_digits=10, decimal_places=2)
    insurance_by_charge = models.DecimalField('Insurance By Percentage Charge', max_digits=10, decimal_places=2)
    midnight_surcharge = models.DecimalField('Midnight Surcharge', max_digits=10, decimal_places=2)
    sanral_charges = models.DecimalField('Sanral Charges', max_digits=10, decimal_places=2)
    sanral_zone = models.CharField('Sanral Zone', max_length=3)
    waybill_insurance = models.DecimalField('Insurance per Waybill', max_digits=10, decimal_places=2)
    sunday_charge = models.DecimalField('Sunday Charge', max_digits=10, decimal_places=2)
    home_delivery = models.DecimalField('Home Delivery', max_digits=10, decimal_places=2)
    re_delivery = models.DecimalField('Re-Delivery', max_digits=10, decimal_places=2)
    online_delivery = models.DecimalField('Online Delivery', max_digits=10, decimal_places=2)
    tech_doc_fee = models.DecimalField('Technology Doc Fee', max_digits=10, decimal_places=2)
    pda = models.DecimalField('PDA', max_digits=10, decimal_places=2)
    mpod = models.DecimalField('MPOD', max_digits=10, decimal_places=2)
    fuel_surcharge_percentage = models.DecimalField('Fuel Surcharge Percentage', max_digits=10, decimal_places=2)
    amount_excl_vat = models.DecimalField('Amount Excl. VAT', max_digits=10, decimal_places=2)
    VAT = models.DecimalField('VAT', max_digits=10, decimal_places=2)
